services:
  agent-report:
    build: 
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "7700:5000"  # FastAPI
      - "8501:8501"  # Streamlit
      # - "8001:8001"  # MCP
    environment:
      - url=https://docs.google.com/spreadsheets/d/19zPaWbW-VuYqhq1ur8vcPoV4EbDKKVDDN84vi4yuOJU/edit?usp=sharing
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
